name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '25 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ABBREV_MATRIX: ['min-stage1']
        SUITE_MATRIX: ['bookworm', 'trixie', 'sid']
        OWNER_MATRIX: ['rubyonracetracks']
        DISTRO_MATRIX: ['debian']
    env:
      ABBREV: ${{ matrix.ABBREV_MATRIX }}
      SUITE: ${{ matrix.SUITE_MATRIX }}
      OWNER: ${{ matrix.OWNER_MATRIX }}
      DISTRO: ${{ matrix.DISTRO_MATRIX }}

    steps:
      - uses: actions/checkout@v3

      - name: Set the parameters
        run: bash ci-parameters.sh

      - name: Run the setup script
        run: bash setup.sh

      - name: Create the Docker container
        run: cd tmp/$ABBREV/$SUITE && bash container_create.sh

      - name: List Docker containers
        run: cd tmp/$ABBREV/$SUITE && source variables.sh && docker ps -a | grep $CONTAINER | awk '{print $1}'

      - name: Start the Docker container and run the check script
        run: cd tmp/$ABBREV/$SUITE && source variables.sh && docker exec -id $CONTAINER sh -c "/usr/local/bin/check"

