name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '25 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ABBREV_MATRIX: ['min-stage1']
        SUITE_MATRIX: ['bookworm', 'trixie', 'sid']
        OWNER_MATRIX: ['rubyonracetracks']
        DISTRO_MATRIX: ['debian']
    env:
      ABBREV: ${{ matrix.ABBREV_MATRIX }}
      SUITE: ${{ matrix.SUITE_MATRIX }}
      OWNER: ${{ matrix.OWNER_MATRIX }}
      DISTRO: ${{ matrix.DISTRO_MATRIX }}

    steps:
      - uses: actions/checkout@v3

      - name: Test the process of accessing Docker image
        run: bash ci.sh
