name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '25 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ABBREV_MATRIX: ['min-stage1']
        SUITE_MATRIX: ['bookworm', 'trixie', 'sid']
        OWNER_MATRIX: ['rubyonracetracks']
        DISTRO_MATRIX: ['debian']
    env:
      ABBREV: ${{ matrix.ABBREV_MATRIX }}
      SUITE: ${{ matrix.SUITE_MATRIX }}
      OWNER: ${{ matrix.OWNER_MATRIX }}
      DISTRO: ${{ matrix.DISTRO_MATRIX }}

    steps:
      - uses: actions/checkout@v3

      - name: Set the parameters
        run: bash ci-parameters.sh

      - name: Run the setup script
        run: bash setup.sh

      - name: Download the Docker image
        run: cd tmp/$ABBREV/$SUITE && bash download-image.sh

      - name: Create the Docker container from the Docker image
        run: cd tmp/$ABBREV/$SUITE && bash container-create.sh

      - name: Start the Docker container
        run: cd tmp/$ABBREV/$SUITE && bash container-start.sh

      - name: Run /usr/local/bin/check in the Docker container
        run: cd tmp/$ABBREV/$SUITE && bash container-test.sh
